language: node_js
env:
- NODE_ENV=test
node_js:
- '8'
script:
- yarn run lint
deploy:
  provider: npm
  email: wojciech.g.krysiak@gmail.com
  api_key:
    secure: lxBpWQtnYkIRnaR55ykfuYCNIsIpo9JLm//zF9bbIcq5Ty4ElosmyQ3rRAeyal1U5N3eZpXxnWZUq4OgaO9q83ErtcNfx53rGR2JvxGkFhf7wwktRH6UgTtmp7EG5v6GTN47JT6gC9OwTKdKT0Sjri0e7I+ZQZk1Kj6f3cJc2VZgrA4AZn3blP3BJI2Ic9P/7Osicwifg1jgbMd/kEMKn/qV/saR+NgnDFR3peuBlbzOn0SnFjX+7b/dpxDPJo11/XZ4OxPK8TYCc05Pi50Xq07FnZm5pWk1/wvOKCnvfo4HaiozIBUY/DLI6N0bLczS6Fc+ELjZ/Tk7Vptv1Dxar/1HNn5mIfJw9TfLIWEXp+1c1XVkqXTbLU3liUeRaxth545xFRstZaUtoRwKU845hkMbiTcpzygfCwS/+03YK5ddMonU28GY7TgeemAIyLEzxEhROhwEgWAieWFiOtdzjWj0PvUV3VhuqaTDQ/BAgCCzxqm3mgNW81Wq/zZXrOe908aTIMmHPzsVxc8l6FFC+cbaF2TrqQxAwohnBi1UpPtZ2w66kRC2iKs33tg2x6EGv7Ja6AiomNejn9XNXjtM0Ve1lQhDYkPJ4NHGc/ho9Fi9nVIQU7+1qkC0opHUJaTopF2aQQwLvn2HFg0W/xG6PKWpPbanrqLOQZ9/OdPbBU0=
  on:
    tags: true
    repo: SoftwareBrothers/admin-bro-expressjs
